spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bate_ponto
    username: bateponto
    password: bateponto
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
